BEGIN;

DROP TABLE IF EXISTS security_events;
DROP TABLE IF EXISTS testcase_results;
DROP TABLE IF EXISTS execution_summaries;
DROP TABLE IF EXISTS runs;
DROP TABLE IF EXISTS submissions;
DROP TABLE IF EXISTS testcases;
DROP TABLE IF EXISTS test_groups;
DROP TABLE IF EXISTS problem_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS problem_languages;
DROP TABLE IF EXISTS problems;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS auth_identities;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS SECURITY_SEVERITY;
DROP TYPE IF EXISTS RUN_STATE;
DROP TYPE IF EXISTS TEST_GROUP_VISIBILITY;
DROP TYPE IF EXISTS PROBLEM_VISIBILITY;
DROP TYPE IF EXISTS USER_STATUS;

COMMIT;
