BEGIN;

DROP INDEX IF EXISTS submissions_type_idx;
ALTER TABLE submissions DROP COLUMN IF EXISTS submission_type;

DROP INDEX IF EXISTS problems_difficulty_idx;
ALTER TABLE problems DROP COLUMN IF EXISTS difficulty;

DROP TYPE IF EXISTS SUBMISSION_TYPE;
DROP TYPE IF EXISTS PROBLEM_DIFFICULTY;

COMMIT;
