BEGIN;

DROP TABLE IF EXISTS job_tc_results;
DROP TABLE IF EXISTS job_results;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS workers;
DROP TYPE  IF EXISTS JOB_STATE;
DROP TYPE  IF EXISTS WORKER_HEALTH;

COMMIT;
