/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserRefRouteImport } from './routes/users/$userRef'
import { Route as ProblemsProblemSlugRouteImport } from './routes/problems/$problemSlug'
import { Route as AdminProblemsIndexRouteImport } from './routes/admin/problems/index'
import { Route as AdminProblemsProblemIdRouteImport } from './routes/admin/problems/$problemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserRefRoute = UsersUserRefRouteImport.update({
  id: '/users/$userRef',
  path: '/users/$userRef',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsProblemSlugRoute = ProblemsProblemSlugRouteImport.update({
  id: '/problems/$problemSlug',
  path: '/problems/$problemSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemsIndexRoute = AdminProblemsIndexRouteImport.update({
  id: '/admin/problems/',
  path: '/admin/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemsProblemIdRoute = AdminProblemsProblemIdRouteImport.update({
  id: '/admin/problems/$problemId',
  path: '/admin/problems/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/problems/$problemSlug': typeof ProblemsProblemSlugRoute
  '/users/$userRef': typeof UsersUserRefRoute
  '/admin/problems/$problemId': typeof AdminProblemsProblemIdRoute
  '/admin/problems/': typeof AdminProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/problems/$problemSlug': typeof ProblemsProblemSlugRoute
  '/users/$userRef': typeof UsersUserRefRoute
  '/admin/problems/$problemId': typeof AdminProblemsProblemIdRoute
  '/admin/problems': typeof AdminProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/problems/$problemSlug': typeof ProblemsProblemSlugRoute
  '/users/$userRef': typeof UsersUserRefRoute
  '/admin/problems/$problemId': typeof AdminProblemsProblemIdRoute
  '/admin/problems/': typeof AdminProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/problems/$problemSlug'
    | '/users/$userRef'
    | '/admin/problems/$problemId'
    | '/admin/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/problems/$problemSlug'
    | '/users/$userRef'
    | '/admin/problems/$problemId'
    | '/admin/problems'
  id:
    | '__root__'
    | '/'
    | '/problems/$problemSlug'
    | '/users/$userRef'
    | '/admin/problems/$problemId'
    | '/admin/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProblemsProblemSlugRoute: typeof ProblemsProblemSlugRoute
  UsersUserRefRoute: typeof UsersUserRefRoute
  AdminProblemsProblemIdRoute: typeof AdminProblemsProblemIdRoute
  AdminProblemsIndexRoute: typeof AdminProblemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userRef': {
      id: '/users/$userRef'
      path: '/users/$userRef'
      fullPath: '/users/$userRef'
      preLoaderRoute: typeof UsersUserRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$problemSlug': {
      id: '/problems/$problemSlug'
      path: '/problems/$problemSlug'
      fullPath: '/problems/$problemSlug'
      preLoaderRoute: typeof ProblemsProblemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problems/': {
      id: '/admin/problems/'
      path: '/admin/problems'
      fullPath: '/admin/problems/'
      preLoaderRoute: typeof AdminProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problems/$problemId': {
      id: '/admin/problems/$problemId'
      path: '/admin/problems/$problemId'
      fullPath: '/admin/problems/$problemId'
      preLoaderRoute: typeof AdminProblemsProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProblemsProblemSlugRoute: ProblemsProblemSlugRoute,
  UsersUserRefRoute: UsersUserRefRoute,
  AdminProblemsProblemIdRoute: AdminProblemsProblemIdRoute,
  AdminProblemsIndexRoute: AdminProblemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
